### ISSUE TITLE
Logged-out view: Dropdown menu for "Writer's Resources" has a weird symbol in it.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#217]
Seeing this:

> Discover our resources for tips and tricks on starting and finishing your next great writing project.

Can we remove the symbol between "tricks" and "on"?

**Comment by nanojezra** [comment]
Weird. The only place I am seeing this is on a chromebook.  For future issues please provide and screenshot and information regarding the the browser you are using.
