### ISSUE TITLE
Sign-In: Add username to ways you can log in for traditional sign-in.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#220]
Right now, if you log out and then want to log back in, we only accept your email address if you're using traditional sign-in. Can we allow people to put email address or username in that same field?

**Comment by nanojezra** [comment]
we can, and we should, and it does not follow the design spec

**Comment by timhkim** [comment]
Great! Thank you.

**Comment by timhkim** [comment]
I think this may have broken sign-in? I can't log into the account under "tim_kim+december@nanowrimo.org" using the username or the email address. I even reset my password in case I was remembering it incorrectly, and with the new password I couldn't log in either.

**Comment by nanojezra** [comment]
entering known valid credentials results in receiving the "Invalid username / password" error message

**Comment by nanojezra** [comment]
There was a problem with the backend API code not updating properly.
