### ISSUE TITLE
Sign-In: Google sign-in is showing me a 404 in the pop-up window.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#221]
When I click "continue with google" I get the pop-up window. It allowed me to pick which of my google accounts I wanted to use to sign-in, and then I picked my tim_kim@lettersandlight.org account. It loaded another page in the same pop-up window, with a 404 "Not Found" message.

**Comment by nanojezra** [comment]
The popup displays google created content. A 404 in the popup is most likely the result of an error we have no control over. A screen shot of the error, including the url of the problem page, would be very helpful.

**Comment by timhkim** [comment]
When I'm signing in, I click Sign-In with Google. 

I get this pop-up:
![screenshot 2019-01-07 at 2 41 19 pm](https://user-images.githubusercontent.com/39069145/50797694-7fc64d80-128a-11e9-9769-5ae3564b7371.png)

I select "tim_kim@lettersandlight.org" and then see this pop-up (you'll see the 404 cut off at the top):
![screenshot 2019-01-07 at 2 41 41 pm](https://user-images.githubusercontent.com/39069145/50797708-8a80e280-128a-11e9-9cb0-7afe93a21f06.png)

I close out the pop-up b/c I don't see another way to progress. I then get this dialog:
![screenshot 2019-01-07 at 2 41 50 pm](https://user-images.githubusercontent.com/39069145/50797726-9e2c4900-128a-11e9-9d10-d6f909e81761.png)

**Comment by nanojezra** [comment]
our code base needs to specify the full callback url for google authentication. Currently, the callback url is set to http://ember.nanowrimo.org. Attempting to use google authentication from preview.nanowrimo.org (or any other url) will always display the error.

**Comment by timhkim** [comment]
I'm going to close this ticket in favor of #371.
