### ISSUE TITLE
Forgot Password: Styling adjustments for the text

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#222]
H2: Let's get your password reset

Styling(    font-family: SourceSansPro-Regular,sans-serif;
    font-size: 16px;
    line-height: 1.38;
    letter-spacing: .3px;
    text-align: left;
    color: #979797;): "Please enter your email address below and we'll send you a link so you can reset your password!"

Can we make sure there's not as much space between the above text and the "Email" entering section as there currently is? Big gap right now.

After clicking Submit, can we change the card so the H2 now reads "Great! Check your email."

Then the paragraph styled text is "We've sent you a link to reset your password. Please check your email inbox!"

**Comment by timhkim** [comment]
This look awesome. Can we just put in a little space between the help text and the "Email" form input label?

**Comment by nanojezra** [comment]
test please

**Comment by timhkim** [comment]
Perfect!
