### ISSUE TITLE
Profile: Make adding links to your bio easier.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#225]
Can we:

- [x]  Just show one "link" suggestion in this section instead of the custom ones.
- [x]  Detect if the URL has "Facebook", "Twitter", "Instagram", "Medium", or "Tumblr" in it on our own, and then display as social icons, instead of presenting the specific text boxes?
- [x]  Add "YouTube" (Xand "Wattpad"X) to the above social icon displays?
- [x]  Automatically make the URLs work if a user inputs "instagram.com/nanowrimo" for example? Can't we just add the https:// instead of making the user do it?

**Comment by nanojezra** [comment]
item 3, wattpad does not have a font awesome icon. I will see what I can create

**Comment by timhkim** [comment]
Thank you, Jez!

Tim Kim
Programs Director at NaNoWriMo
he / him / his

Love us? Support us!
Make a tax-deductible donation to National Novel Writing Month today.
http://store.nanowrimo.org/donations

**Comment by nanojezra** [comment]
creating the wattpad graphic is problematic and beyond my ability to add the icon as a font.

**Comment by timhkim** [comment]
Totally. Thanks for trying!! I think we can go with the generic link icon,
then.

Tim Kim
Programs Director at NaNoWriMo
he / him / his

Love us? Support us!
Make a tax-deductible donation to National Novel Writing Month today.
http://store.nanowrimo.org/donations

**Comment by nanojezra** [comment]
I've removed some experimental wattpad code, removed the display of empty social media inputs on the edit form, and merged to production

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
Dang, smashing these. Looks great!
