### ISSUE TITLE
Profile: Styling adjustments in the bio card when a user has ten total favorites.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#226]
You can see what it currently looks like here: https://preview.nanowrimo.org/participants/new-write

- [ ] Can we, by default, add a line break between the fifth book and the first author so it doesn't feel so crowded?
- [ ] If there is long bio text, can we show as much of it as will fit in the card before cutting it off for "Read more" if the card is expanding to fit more favorites?

**Comment by nanojezra** [comment]
test please

**Comment by timhkim** [comment]
This seems like it's working great! Thank you, Jez!
