### ISSUE TITLE
Profile: Change auto-display of "See more" in the Author card for the bio.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#234]
Currently, if you go to your profile for the first time, the Author card auto-displays a "see more" link, even though there's no text to see more of.

Can we make sure this "See more" link doesn't appear? And can we include prompt text for an empty author bio that reads "<a href="TKWHATEVER URL THIS IS TO OPEN THE PROFILE EDIT>Tell your fellow writers a little bit more about yourself!</a> What better way to practice for your book jacket blurb?"

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
Okay! This looks exactly like what I asked for, but I have additional thoughts, haha.

Can we use similar styling as on the project details page for the text that reads "You haven't told us much about your new project. Fill out your project details here."? For example: https://preview.nanowrimo.org/participants/tim-kim/projects/a-new-hope-986c23f1-5042-45a4-9e1b-42823c6306eb

Maybe at font-size 16px though. In keeping with that styling, I'd amend my unlinked text to "Ready to practice for your book jacket blurb?" and then linked text that reads "Tell your fellow writers more about yourself."

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
Perfect. Thank you, Jez; this looks great!
