### ISSUE TITLE
Profile: Styling change for text in the Personal Achievement badge panel

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#236]
Can we change the help text to "Click on a badge to award it to yourself! Click on it again to remove it." and then change the styling to "form-instruction" styling?

**Comment by nanojezra** [comment]
form-instruction from where?

**Comment by nanojezra** [comment]
found it

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
Looks great!
