### ISSUE TITLE
profile edit dialog does not appear when the user clicks the edit bio gear 

### ISSUE THREAD

**Issue by nanojezra** [nanowrimo/nanowrimo_frontend#241]
steps to reproduce:
1. sign out
2. sign in
3. navigate to profile
4. click the 'gear' under the 'About' section
expected result: the edit form should be displayed 

weird note; refreshing the page results in the edit form being displayed

**Comment by nanojezra** [comment]
dagnabbit! I can't reproduce in production

**Comment by nanodave** [comment]
I'm not seeing the error on my local dev environment, either.

**Comment by nanojezra** [comment]
now I'm not seeing the error :)
