### ISSUE TITLE
Add a shadow to avatar with an edit icon to indicate you can change it.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#249]
Currently, if you hover over the profile avatar, the tab at the the bottom left of the entire left column flips and shows you the settings gear.

Can we instead cue a shadow over the avatar with a centered edit icon (maybe this one? https://fontawesome.com/icons/edit?style=solid).

**Comment by nanojezra** [comment]
ready for testing 

This is certainly far better than the curlygear, although now the plate image is asking for a similar treatment

**Comment by timhkim** [comment]
This looks great. I thiink the plate is okay, but I would really like to apply this to the novel covers on the projects page (#250), and the big cover in the project details pages.

**Comment by timhkim** [comment]
You're right! Let's apply it across the board to the plate image, as well.

(I'm not seeing this on the preview site, currently, but I'll give it a minute?)

**Comment by timhkim** [comment]
I'm going to close this in favor of #250.
