### ISSUE TITLE
Add edit indicators to a displayed project cover on the projects page.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#250]
For example on this page: https://preview.nanowrimo.org/participants/tim-kim/projects

Currently, you _can_ click on the novel cover to edit it, but there are no indicators -- the cursor doesn't even change. Can we add the usual cursor change, and also do a similar treatment as described in #249? 

Let's add a shadow on hover, and the edit icon.

**Comment by timhkim** [comment]
I'd like to see this same treatment on all customizable images, including:

- [ ] The novel covers on the projects list page.
- [ ] The really big novel cover in the project details page.
- [ ] The cover plate, as suggested by Jez.

Jez, I think you mentioned this had been applied to at least a couple of the above, but I'm not seeing it on the preview site?

**Comment by nanojezra** [comment]
this is currently only applied to the user avatar

**Comment by timhkim** [comment]
Ah, okay. I think what you said in the other ticket makes sense, and would like to apply it to all the image uploads as described above.

**Comment by nanojezra** [comment]
ready for testing 

this leaves 2 instances in the app where a project cover does not trigger the cover edit modal; the tilted cover at the top of the project view, and the tilted cover in the count updater

**Comment by timhkim** [comment]
Ah, interesting. I feel like in both those cases, it functions more like an icon than a customizable display of your cover... but I'm open to making those editable as well.

**Comment by nanojezra** [comment]
the image on the session counter certainly doesn't need this treatment, but the image on the project view, if it is a trigger, would be the only way to change the cover if the user has not added any information about the project (and the large image is not visible)

**Comment by timhkim** [comment]
That makes sense! Let's add edit indicators to that tilted cover at the top of the project view. Thanks for the thoughts, Jez!
