### ISSUE TITLE
Change the duration select input on the Goals tab of the Project Announce/Edit

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#252]
Currently, there are two inputs: a calendar-style start date, and then an integer-input duration of days.

![capture](https://user-images.githubusercontent.com/39069145/51050444-b00d3500-1585-11e9-9654-7ab6e98e5a9a.PNG)

After continued exposure, I think I'd really prefer consistency, and allow a user to set an end date rather than inputting "30 days" or something like that. Can we either:

1. Change to "What's your end date?" with the same calendar dropdown input?
2. Do it all in one input? For example, on the United Airlines page (https://www.united.com/en/us/), there's an input "Dates", and on-click a calendar dropdown appears, and you can select both a start date and an end date in the same go, and the duration is lightly highlighted.

**Comment by nanojezra** [comment]
is the "end" date the last day of the user's event or is it the time that the event ends?

**Comment by timhkim** [comment]
So, for example, for NaNoWriMo, I would put the end date as November 30, which means that's the last day of the event.

**Comment by timhkim** [comment]
This is working, and it looks so good! Thank you, Jezra.

One additional thing: can we make sure to duplicate this across the board? It needs to be applied to the screens when you:

1. Try to edit your goal.
2. Try to create a new goal for an existing project.

**Comment by nanojezra** [comment]
On Wed, 16 Jan 2019 08:48:41 -0800
timhkim <notifications@github.com> wrote:

> This is working, and it looks so good! Thank you, Jezra.
> 
> One additional thing: can we make sure to duplicate this across the
> board? It needs to be applied to the screens when you:
> 
> 1. Try to edit your goal.
> 2. Try to create a new goal for an existing project.
> 

Yea, that was my plan for today.

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
This is mostly working except for styling! Can we match the styling of the project edit/create pop-up? Also, specifically, the calendar icon is not displaying when trying to edit or create a new goal. Image below:

![newgoal](https://user-images.githubusercontent.com/39069145/51337251-703dc600-1a3b-11e9-8ded-b2b6eb663598.PNG)

**Comment by nanojezra** [comment]
that is a different form and should probably be a different issue. That being said, code for this was merged yesterday, but obviously it didn't get deployed properly

**Comment by nanojezra** [comment]
OK, test away!

**Comment by timhkim** [comment]
Woohoo! The specific duration inputs look great now. There's a weird lack of margin happening, in particular on the left side? Attaching two pics below for comparison:

![edit](https://user-images.githubusercontent.com/39069145/51399221-4eefdf00-1afa-11e9-88b9-55a55a245528.PNG)
![create](https://user-images.githubusercontent.com/39069145/51399224-50210c00-1afa-11e9-8322-3b794bfbb054.PNG)

**Comment by nanojezra** [comment]
yup, there is a lack of consistency across forms

**Comment by nanojezra** [comment]
I have added what appears to be margin on most other forms. 
For the record I still prefer 'start date' and 'duration' for the input as it is error proof. 

please test

**Comment by timhkim** [comment]
I get it! Let's see how users react to it, and if we start seeing a lot of errors or requests for a different type of input we can adjust.

Otherwise, the new margins look great and more consistent with the other forms.

**Comment by nanojezra** [comment]
There will most likely be no user feedback because it is currently
functional, the user is notified when they make a selection that will
result in an error, and the user doesn't know there is a design
alternative that is not capable of generating an error.

**Comment by nanojezra** [comment]
Boiled down, it is the difference between:
I want to start on X date, and write for Y days
and
I want to start on X date, and end on Y date

Both have benefits, and both have issue. 

Aside from that, the 'last day' not being counted is certainly an
issue.

**Comment by timhkim** [comment]
I'm going to close this and open a new ticket for the calculation issue.
