### ISSUE TITLE
Adjust the font styling in the calendar dropdown when setting dates in the Project Goal Announce/Edit form

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#253]
Is it possible to make the font the Source Sans Pro we're using everywhere else on the site? It's sticking out a bit.

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
This doesn't seem like it's working but it is absolutely not a priority.

**Comment by nanojezra** [comment]
it probably needs horrid 'per browser' specific styling :/

**Comment by timhkim** [comment]
Would that mean it's not possible?

**Comment by nanojezra** [comment]
It *should* be possible, but I will need to check on the documentation
for styling default calendar widgets for various browsers. The other
option would be to use a 3rd party calendar widget that can be styled
to our liking, and I'm doubtful that such a thing exists.

**Comment by timhkim** [comment]
Okay! I was only asking b/c I was debating closing the ticket completely.
Let's leave it at a super low priority for now.

Tim Kim
Programs Director at NaNoWriMo
he / him / his

Love us? Support us!
Make a tax-deductible donation to National Novel Writing Month today.
http://store.nanowrimo.org/donations

**Comment by nanodave** [comment]
The calendar styling is browser-specific, and (hopefully) designed to be optimal for that browser. As Jez said, fixes will have to be browser-by-browser, and will be overriding existing browser styles.  I didn't even notice the typeface differences, and I'm one of those designy-type-people. May we close this? If it's still bugging you six months from now you can create a new ticket. :)

**Comment by timhkim** [comment]
Yes!
