### ISSUE TITLE
When I try to create a second project, it seems to disappear.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#254]
I have an existing project. I then click "Announce a new project" in the bar below my existing project. A pop-up shows up, and I fill in all my project details and click "Save Project". The pop-up disappears. The page shows my new project but it's replaced my existing one rather than being added as a second project. 

When I refresh the page, my new project disappears entirely, and my previously existing project is displayed again.

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
Okay! This is working now, but when it first shows up on the page, the goal shows "Write NaN Words" and the count displays as "0/NaN WORDS"

![screenshot 2019-01-14 at 9 15 10 am](https://user-images.githubusercontent.com/39069145/51128943-ed6bff80-17dd-11e9-9c8b-bc454d1cf7f2.png)

When I refresh the page or take another action, then it corrects itself.

**Comment by timhkim** [comment]
This is working now!! Thank you!
