### ISSUE TITLE
Not able to see the progress updater when I have an active goal.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#257]
I created a new project, with a new associated goal. I set the start date for 1/15/19. I don't see the progress updater in my nav.

I changed the start date back to 1/14/19 in case that would change things, and I still don't see the progress updater.

**Comment by timhkim** [comment]
Here's the goal I'm trying to update if that helps: https://preview.nanowrimo.org/participants/tim-kim/projects/draft-1/goals

**Comment by timhkim** [comment]
I can see the updater now, but when I click it, there's no dropdown!

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
This is displaying now; thank you!
