### ISSUE TITLE
Excerpt display for a project doesn't hold onto the spacing that a user inputs in the "create/edit" project form.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#258]
You can see this here: https://preview.nanowrimo.org/participants/tim-kim/projects/draft-1

I had paragraph spacing, but the display just pushed everything together. Should be displayed as:

"I met Adem when I was sixteen, but I ran away from him for a long time because I knew you wouldn't like him. Well. I think you could have liked him; what you wouldn't have liked was the way that I liked him, how my gaze would skitter away from him, reacting to a magnetic force.

When I was nineteen, I was stocking Cheez-its in the liquor store aisle, rhythmic and day-dreaming, and Adem snuck up on me -- I didn't even hear his pulse -- and tapped me on the shoulder, and he said, "Hey, you dropped this," and he had this five-dollar bill folded in half in his hand.

He caught me by surprise; enough so that my eyes lingered, caught on the gold hoops in his ears, the stud in his nose. And, straight up, I was confused: I told him, "I don't carry cash, bro," this bass in my voice, all my defenses auto-deploying. I had learned to mimic this voice really well. "Thanks anyway.""

**Comment by nanojezra** [comment]
Oh that Adem, sneaky like a hobbit.
I have created a template helper to replace newline characters with an HTML line break. However, this requires rendering raw HTML, so I have attempted to strip HTML from the text before applying the linebreak tags

**Comment by nanojezra** [comment]
please test for excerpt. 
should this be applied to summary?

How did the narrator get a job in a liquor store at 19?

**Comment by timhkim** [comment]
Hahaha, I should send you my actual novel draft for logic questions like this.

Yes, to summary, please.

**Comment by nanojezra** [comment]
summary should be working now

perhaps the narrator is Canadian.

**Comment by nanojezra** [comment]
one more time. :)

**Comment by timhkim** [comment]
Perfect! Thank youuuuuuuu

**Comment by nanojezra** [comment]
closing tickets is all the thanks I need
