### ISSUE TITLE
Adjust the styling for the delete confirmation pop-up.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#269]
- [ ] - Can we use Source Serif Pro for the body font here?
- [ ] - The margins should be the same as other pop-up modals like this.
- [ ] - Can we add a period to "Yes, delete my project and its goals." and a space to "No, never mind."?
- [ ] Can we expand the buttons here so that "Yes, delete my project and its goals." gets some more room? We can expand "No, never mind." the same to keep them equal if we need to.
- [ ] Can we change the color on "Yes, delete..." to the normal green we use?

**Comment by nanojezra** [comment]
Instead of making custom one off styling for this confirmation modal's buttons, I would like to suggest removing the redundant text from the Yes/No buttons as this will ensure that all confirmation modals have consistent button size, button shape, button text, and button location.  

side note, what is "whiteout"?

**Comment by timhkim** [comment]
Ah, yeah, that's fair. Let's do that.

Given your question about the whiteout text, haha, let's make it less cute and change that last bit of text. "Are you sure you want to do this?"

**Comment by nanojezra** [comment]
This weekend, I read a few research backed HIGs and based on the HIGs, this confirmation dialog should be something like the following:
body:
  Delete [name of project]? (the action question for the user)
  Deleting [name of project] will also delete the project's goals and progress (extra 
  messaging for the user regarding the outcome of the action) 

actions:
  green nano button with text of "delete" or "delete this project" 
  plain text link with text of 'cancel' (styling should match the 'cancel' link from project creation form)

**Comment by timhkim** [comment]
Oh, awesome! Thanks for doing more research into it.

That sounds great to me! Let's go for it.

Tim Kim
Programs Director at NaNoWriMo
he / him / his

Love us? Support us!
Make a tax-deductible donation to National Novel Writing Month today.
http://store.nanowrimo.org/donations

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
Again, thanks for the research and suggestion! This looks so much better, and is way clearer.
