### ISSUE TITLE
Link the goals displayed on the goals page to their respective stats dashboards.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#270]
For example, on this page: https://preview.nanowrimo.org/participants/tim-kim/projects/draft-1/goals

I think it would be ideal if clicking on the entire actual goal takes you to the stats dashboard for that goal.

**Comment by nanojezra** [comment]
I would suggest making a "show stats for this goal" link in the goal's dropdown menu thingy (or someplace else on the goal display listing) to make it obvious to the user exactly what will happen when the user clicks/touches an element on their screen..

**Comment by timhkim** [comment]
Hmm... I totally get why you're suggesting this, but to me it feels a little weird that clicking on the thing itself doesn't do anything. Oh, why don't we do something similar to the projects display, and have the title of the goal clickable, and have _that_ take you to the stats dashboard?

**Comment by nanojezra** [comment]
It won't be explicit in notifying the user what happens when it is clicked, but it will work. The link will need to look like a link.

**Comment by nanojezra** [comment]
for consistency that follows best design and usability practices, we need to define a style for links.  I don't care what the style is or how much it doesn't look like a link that users are accustomed to, as long as all of our links look the same.

**Comment by timhkim** [comment]
Fair! Can we define a "Card Link"? It'd be ideal if it looked the same as the project title links on the Projects page.

**Comment by nanojezra** [comment]
it would be ideal of all links in cards looked the same in regards to font, color, and decoration. I'm going to make the link styling a new ticket.

**Comment by timhkim** [comment]
This should match the "div-class: project title" styling! It's pretty close, but there should be no font-weight, and the font-size should be 20px.

**Comment by nanojezra** [comment]
Preferably it would match a generic sub style for a list item element. Something like: ".list-item .primary-text" That way there is only one location for editing/developing the style, and there will be less development time spent on styling as more lists are displayed on the site.  I will check the zepelin design to see if all lists use the same style of the primary text.

**Comment by nanojezra** [comment]
test please

**Comment by timhkim** [comment]
The styling looks great, but the card looks like it got bigger, weirdly? The bottom margin is inexplicably large, and the image is no longer aligned at the bottom. Example here: https://preview.nanowrimo.org/participants/collectonian/projects/maid-maleen/goals

**Comment by nanojezra** [comment]
ready for testing

**Comment by timhkim** [comment]
Sweet! This looks great.
