### ISSUE TITLE
Remember if a user left "more details" in the session updater expanded or collapsed.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#272]
If I expanded "more details" the last time I reported a session, I'd love for the dropdown to remember that and have it auto-expanded the next time I click that updater.

**Comment by nanojezra** [comment]
ready for testing

**Comment by timhkim** [comment]
This seems to only be showing as expanded, regardless of whether I collapsed it or not.

**Comment by nanojezra** [comment]
the user's choice to show/hide the addition details is only updated in the database when the user submits the session data

**Comment by timhkim** [comment]
Okay! I don't know what I was doing before, but testing now with that knowledge in mind, this seems like it's working. Thanks for the clarification!
