### ISSUE TITLE
Add more audible/visual cues when your timer goes off in the progress updater.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#277]
Can we add a sound effect? I'm down for Jezra's usual, or something like this: https://freesound.org/people/tjandrasounds/sounds/201589/

Also, is it possible to make the browser tab flash in some way when the timer goes off and you're in another tab?

**Comment by nanojezra** [comment]
There already should be a sound when the timer hits 0, and most browsers will flash a sound 'icon' on a tab with audio.

**Comment by timhkim** [comment]
Ah okay. I'm in Chrome on a Windows computer at home, and I'm not getting any sound, or a sound "icon" in the tab.

**Comment by nanojezra** [comment]
I'm not getting any sound from the production server either

**Comment by nanojezra** [comment]
the audio files aren't making it to the production server

**Comment by nanojezra** [comment]
ready for testing

**Comment by timhkim** [comment]
Audio seems like it's working! Aw, that familiar Jezra bing, haha.

I'm going to close this ticket for the audio cue, and may open a separate one for beefing up the visual one.
