### ISSUE TITLE
"Words needed today" stat is not recalculating if you're ahead or behind.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#278]
For example, for a usual 50K/30-day challenge, this stat is showing 1,667 words needed today, no matter what your progress is. 

This should recalculate at midnight for all active goals, and take the total words left to be written and divide that by the remaining days in the goal. So if I wrote 1,000 words on Day 1, at midnight for Day 2, this should update to show (50,000 - 1,000) / 29 = 1,690 (rounded). 

Then this should act as usual, subtracting any word-count updates on day 2 from this number until it reaches zero.

**Comment by nanojezra** [comment]
So it needs to display "total words needed today to hit the par line"
and not "total words needed to today to reach the daily goal of 1667"?

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
I'm testing this, and will report back tomorrow to make sure it continues to calculate correctly.

**Comment by timhkim** [comment]
One bug here -- for past goals that have been completed, this now displays a number usually in the millions. 

Attaching a screenshot below as an example. Can we display "0" or like a "--" for goals that have reached their deadline? 

![screenshot 2019-01-29 at 11 57 29 am](https://user-images.githubusercontent.com/39069145/51936496-2bac1600-23bd-11e9-8ae7-11633da4a73d.png)

**Comment by nanojezra** [comment]
test please

**Comment by timhkim** [comment]
Looking good! Thank you, Jez.

**Comment by timhkim** [comment]
I think our miscommunication happened early on in this ticket. You asked "So it needs to display 'total words needed today to hit the par line' and not 'total words needed to today to reach the daily goal of 1667'?" and I said yes, which was wrong! 

The daily word-count goal is supposed to encourage people to write and break down their goal into smaller chunks. So rather than being like... "this is what it takes to meet your par line today", it should be "this is the new pace you need to be writing at to hit your goal in the time remaining".

**Comment by nanojezra** [comment]
What the number is supposed to encourage is irrelevant. I need to know how you want the number computed, and how the percentile for the circular graph should be computed.

**Comment by timhkim** [comment]
"This should recalculate at midnight for all active goals, and take the total words left to be written and divide that by the remaining days in the goal. So if I wrote 1,000 words on Day 1, at midnight for Day 2, this should update to show (50,000 - 1,000) / 29 = 1,690 (rounded).

Then this should act as usual, subtracting any word-count updates on day 2 from this number until it reaches zero."

To add to this initial post, if I haven't written anything, at midnight on Day 2, this should update to show (50,000 - 0) / 29 = 1,724 (rounded). Then, act as usual, subtracting any word-count updates on day 2 from this new par until it reaches zero.

My previous comment assumed that: 1. you would read the history of this bug, and 2. you had an interest in knowing the purpose of the features we build. If you're uninterested in the impact on the user, that's surprising to hear.

**Comment by nanojezra** [comment]
Getting people to write more is the entire goal of our organization and website.  When writing tickets please focus on the technical aspects of the issue. Questioning my interest in regards to displaying a number to a user is, in my opinion, outside the scope of the requested computation.

**Comment by timhkim** [comment]
Fine, Jez.

**Comment by nanojezra** [comment]
ready for testing on staging 

The math:

count_per_day_to_finish_on_time=(total_remaining_count+todays_count )/ total_remaining_days_including_today 

count_needed = count_per_day_to_finish_on_time - todays_count
percent = todays_count*100/count_needed

**Comment by timhkim** [comment]
Thanks, Jezra! Will update with results from testing tomorrow.

**Comment by timhkim** [comment]
I think this is working, but I'm going to test again tomorrow with a more complicated set-up.

**Comment by timhkim** [comment]
This worked as expected again today. I think we can push to production!

**Comment by nanojezra** [comment]
merged to production
