### ISSUE TITLE
Address unavailable links in the mini-nav

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#282]
In the mini-nav at the very top, can we change the link for "Help Center" to read "Email Help Desk" and link it to "help@nanowrimo.org"?

Then, let's hide:

- [x] - [ ] search bar
- [x] "Get Involved"

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
This looks good! Sorry, I had the wrong link for the help desk. Can we change that link to: "support@nanowrimo.zohodesk.com"?

**Comment by nanojezra** [comment]
it should be opening the user's email client. Does this mean you are testing on a chromebook and the link is going gmail.com?

**Comment by timhkim** [comment]
LOL, whoops. Yes, sorry for not supplying more details.

On a Chromebook -- I click that link and it opens my gmail account in the same browser tab.

**Comment by nanojezra** [comment]
When you are on a real computer, it will open the email client. Opening the link in a new tab will result in non-chromebook browsers having an empty tab.  How would you feel about a low priority ticket for detecting if the user is on chromebook?

**Comment by timhkim** [comment]
Yeah, way low priority is fine. I'll create a new ticket for that and then close this one once the new email link is in.

**Comment by nanojezra** [comment]
ready for testing

**Comment by timhkim** [comment]
Great! Thank you!
