### ISSUE TITLE
Address unavailable links in the main nav

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#283]
- [ ] Under "My NaNoWriMo", please hide "Buddies".

Under "Community":

Is SSO for Discourse going to be available tomorrow? It doesn't seem like it's working, but I don't know if that's because there needs to be a change in the URL for that "Forums" link? If not, let's hide this, please.

Under "Writer's Resources":

- [ ] Hide "NaNo Prep"
- [ ] Redirect "Pep Talks" to https://nanowrimo.org/pep-talks
- [ ] Redirect "Offers" to https://nanowrimo.org/sponsor-offers

In the icon options:

- [ ] Hide the NaNoMessages envelope icon
- [ ] In the dropdown for the username, hide the "Activity Log" link.

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
This looks good! Thank you.
