### ISSUE TITLE
Goals display isn't correctly showing the associated goal for each project until you refresh the page.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#286]
Many of my projects have been imported to my new profile. When I:

Go to my projects page (https://preview.nanowrimo.org/participants/tim-kim/projects)
Click into any project
Click the "Goals" tab

I see the last goal I displayed, even if it's incorrectly associated with the project, until I refresh the page.

**Comment by nanojezra** [comment]
test please

**Comment by timhkim** [comment]
This is looking great. Thank you for doing that!
