### ISSUE TITLE
Styling to allow users to more easily edit their project details page.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#289]
Example of a project details page: https://preview.nanowrimo.org/participants/tim-kim/projects/this-is-the-year-of-no-titles

If you're viewing a project you created (versus the project of a buddy), can we:

- [ ] In the "Excerpt" card, can we cue a settings wheel flip-up in the bottom left corner that will again cue the "edit project details" form if clicked?

**Comment by nanojezra** [comment]
the summary area isn't designed to allow room for the flippy gear.  there is going to be overlap problems with the external link to pinterest

**Comment by timhkim** [comment]
Yup; you're right. 

Amending the original body of the ticket.

**Comment by timhkim** [comment]
Thank you, Jez! This looks good.
