### ISSUE TITLE
"Fill out your project details" link not functioning on the Project Details page.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#290]
If you have an empty project details page (ie https://preview.nanowrimo.org/participants/tim-kim/projects/testing-again), there's a big CTA link that reads "Fill out your project details here."

That link is not currently triggering the project details form.

**Comment by nanojezra** [comment]
ready for testing

**Comment by timhkim** [comment]
Woohoo! Thank you!
