### ISSUE TITLE
Data import is messing with word counts 

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#292]
So, for example, on Katharine's page (https://preview.nanowrimo.org/participants/katharine-gripp/projects)

All the Camp project counts are incorrect, one of the NaNo project counts is incorrect.

Starting from the bottom up:

**"The Forgotten Elementals"** Camp, April 2014
Currently shows 1,050 words, should be showing 19,709 words.

**"The Forgotten Elementals, part 1"** NaNo, October 2014
Showing 0, should be 50K

**"The Forgotten Elementals, part 2"** NaNo, October 2016
Correct.

**"Little Victories"** Camp, March 2017
0 pages, displayed as 0 words

**"I'm going to finish this bloody novel this time. For real."** Camp, June 2017
Showing 1, should be 3,005

**"The Forgotten Elementals, Pt. 2"** NaNo, October 2017
Correct.

**"Finishing the thing!"** Camp, March 2018
Showing 10,124 words, should be 660 minutes

**"The adventures of Elvia and Cauldevere"** Camp, June 2018
Showing 50,511 words, should be 9,515 words

**"The Night Dances"** NaNo, October 2018
Correct.

**Comment by nanodave** [comment]
Katharine's import is working properly now. Next: testing with select MLs.

**Comment by timhkim** [comment]
Closing in favor of https://github.com/nanowrimo/api/issues/27
