### ISSUE TITLE
Stats calculations are not including the goal deadline date as an additional day.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#294]
We say "When is the last day you're writing?" for the end date when someone is setting a goal, but we're not counting it as a day of writing in the stats, which we should. 

So, for example, if I set a goal for November 1 and an end date of November 30, the stats dashboard is representing 29 days of writing instead of 30.

**Comment by nanojezra** [comment]
test please

**Comment by timhkim** [comment]
Hm. I created a new novel, with a new 50K goal for 4/1/2019 - 4/30/2019.

I clicked into the Stats dashboard, and it's not loading at all. I'm getting a spinning loading circle in the browser tab but just the background color in the window itself.

**Comment by timhkim** [comment]
This seems like it's working now as well!
