### ISSUE TITLE
Projects page is not displaying progress in the progress bars.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#296]
The data import seems to work great, and the word count in text is correct. However, the progress bars are all empty as if the word count was zero.

For example: https://preview.nanowrimo.org/participants/tim-kim/projects

All the progress bars are empty.

ETA: Can we also make sure to cap the progress bar at the goal? So if they overachieved, we shouldn't reflect that, we should just reflect a full bar. Seeing wonky progress bars here, for example: https://preview.nanowrimo.org/participants/mona-trimble/projects/the-washed-up-welder/goals

**Comment by nanojezra** [comment]
test please

**Comment by timhkim** [comment]
Woohoo! This looks awesome. Thank you, Jez! I'm going to make a separate ticket about the wonkiness on the goals tab.
