### ISSUE TITLE
Make the synopsis on project details pages scrollable.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#297]
Discovered when I was testing #258. For an example, see here: https://preview.nanowrimo.org/participants/tim-kim/projects/keep-it-going

Can we do a line limit? Like 15 lines?

**Comment by nanodave** [comment]
How about making the div content scrollable? This will also solve whatever comes up in the migrations.

**Comment by timhkim** [comment]
Oh yeah, that's way better! Let's do that.

**Comment by nanojezra** [comment]
I'm striking this one while the iron is hot

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
So much better! I'm seeing a wee bit of overlap over the "Genres" label. For example, here: https://preview.nanowrimo.org/participants/collectonian/projects/deviations

**Comment by nanojezra** [comment]
the problem gets worse as the project gets more genres; and the genres will eventually spill out of the container.

**Comment by timhkim** [comment]
Totally seeing this, too. Could we limit the space that genre bit takes up, and make that space a scrolling container, as well? 

https://preview.nanowrimo.org/participants/tim-kim/projects/let-s-test

**Comment by nanojezra** [comment]
that is going to look quite cluttered if/when all of the scroll bars are present

**Comment by nanojezra** [comment]
I'm going to try setting the area to only scroll if there are more than 2 lines of genres

**Comment by timhkim** [comment]
Cool! I'd say like... 95% of people aren't going to have this many genres, but yeah, either a scroll, or Shelby suggested we could put in an ellipsis icon, and then display the rest in a hover?

**Comment by nanojezra** [comment]
expand on hover, aside from being desktop only, will result in something getting pushed around on screen unless it is in some sort of floating div.  And that is a lot of dev just to display genres in a inflexible design layout.

**Comment by nanojezra** [comment]
available for testing
It does not look good

**Comment by timhkim** [comment]
It works! Thanks, Jez.
