### ISSUE TITLE
Stats: The graphs on the stats dashboard don't always adjust to the timelines of the goals they're displaying.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#309]
- If you have a primary project set, go to "My NaNoWriMo" --> "Stats"
- Your graphs will display according to the timeline of your active goal.
- Using the dropdown submenu, select a different writing project and/or goal.
- Your graphs will react, but the timeline of the display will still be according to the initial project viewed.

You can also:

- Go to one of your projects.
- Go to the Goals tab. 
- Select a goal.
- The stats dashboard will correctly display the timeline in your graphs.
- Use the dropdown submenu to select a different writing project/goal for the dashboard.
- The graphs will again react, but continue to display the timeline for the initial goal viewed.

**Comment by nanojezra** [comment]
please test

**Comment by timhkim** [comment]
Perfect. Thank you, Jez!
