### ISSUE TITLE
Stats: Incorporate the empty state cards.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#310]
You can see some of them here: https://app.zeplin.io/project/5abe9c057d3a890444082509/screen/5abea0269ebd524a37712663

Currently, we're just showing empty spots. Can we:

- Add the empty state cards
- Push the "How I Feel" card to the left, and leave a gap for the future "Sprints" card to the right of it instead of in the middle of that row?

**Comment by timhkim** [comment]
@nanodave Could we possibly get the art for this here?

**Comment by nanodave** [comment]
Sent via email

**Comment by nanojezra** [comment]
deployed to staging

however, the grayed out smiley face is still missing

**Comment by timhkim** [comment]
Great! Thank you, Jez. A few small things:

1. For "Where I Write" and "How I Feel", can we remove the line breaks and let the text run without them? 
2. Can we change the text for the empty state of "How I Feel" to "You're a closed book. Any chance you're writing a mystery?"
3. I will get the grayed-out smiley face for you! Thank you for the current placeholder.

**Comment by nanojezra** [comment]
1. yes
2. yes please!
3. thank you

**Comment by nanojezra** [comment]
back to 1.
Should the same treatment be applied to When I Write?

**Comment by nanojezra** [comment]
Clarification needed:
it is just the text in the empty state that needs breaks removed?

**Comment by timhkim** [comment]
Oh, good question. Yes, let's just apply to the text in the empty states, including the empty state for "When I Write".

**Comment by nanojezra** [comment]
ready for testing

**Comment by timhkim** [comment]
These look great! Two things:

Can we make all the text for empty-state cards copy the font color for the subcard faces? It's #979797.

For the "At this rate..." card, can we replace "At this rate you'll be done on undefined NaN!" with "Start writing to find out when you'll finish!"

**Comment by nanodave** [comment]
Is this done?

**Comment by timhkim** [comment]
This is done except for:

> For the "At this rate..." card, can we replace "At this rate you'll be done on undefined NaN!" with "Start writing to find out when you'll finish!"
