### ISSUE TITLE
Styling for the pop-up when you're creating a new goal for an existing project.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#321]
To see the pop-up:

1. Go into an existing project.
2. Go to the Goals tab.
3. Press "Create New Goal".

A couple of issues on this pop-up:

- [ ] They styling for "What is your goal" is off. The input box is not styled correctly, and the select for "words" vs "hours" is also off. Including images below.

- [ ] Can we change the workflow for associating with an existing event? It'd be great if the checkbox remains, but the dropdown for the event select is grayed out. Then the flow should be:

1. Check the checkbox.
2. The dropdown un-grays and becomes usable. The rest of the options gray out as they currently do.
3. You select the event.
4. The data we fill in changes.
5. You click "Save Goal".

Currently, we're getting confusion from people who think they _have_ to associate any new goals for past projects with an event.

**Comment by timhkim** [comment]
![screenshot 2019-02-07 at 9 37 27 am](https://user-images.githubusercontent.com/39069145/52430929-081f5480-2abc-11e9-86a6-656b3b3b4ebb.png)
![screenshot 2019-02-07 at 9 37 20 am](https://user-images.githubusercontent.com/39069145/52430932-0a81ae80-2abc-11e9-8b99-597fe6ae9ba3.png)

**Comment by nanodave** [comment]
Moved to other list
