### ISSUE TITLE
Stats: Words Needed Today doesn't seem to be working?

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#322]
It seemed like things were kosher, but now I'm only seeing zero for my active projects.

My project "The Journey Begins" has a goal "My New Goal". My current word count is 10,200, and my graph says my path to success should be at 45K today. My top middle stat says "0 words needed today".

I also created a brand new goal for "Let's Test" called "Goal 2: Prep". 0 word count; path to success is 125. Showing "0 words needed today" again.

**Comment by nanojezra** [comment]
ready for testing ...

we should probably revisit what this displays, if anything, when it is not possible for a user to update their count

**Comment by timhkim** [comment]
Maybe that's what did it? We had a ticket like that last week. I think we tried to make it display zero when the project wasn't active.

**Comment by nanojezra** [comment]
On Thu, 07 Feb 2019 13:21:03 -0800
timhkim <notifications@github.com> wrote:

> Maybe that's what did it? We had a ticket like that last week. I
> think we tried to make it display zero when the project wasn't active.
> 
it certainly was. the bug was a failure to property determine if the
challenge had ended.

**Comment by timhkim** [comment]
Cool; I think this works! Thank you.

**Comment by timhkim** [comment]
I think this got messed up again, maybe during the whole staging mix-up? 

My stats dashboard for my goal to write 50,000 words by March 22 (26 days including today) is telling me I need to write 8,335 words today. I should need ~1,923 words.

**Comment by nanojezra** [comment]
when does the goal start? what is the current count?

**Comment by timhkim** [comment]
The start date is February 21, and the current count is zero!

**Comment by nanojezra** [comment]
if the count is zero, then the 'needed today' number will be the value of the goal line for today.

**Comment by nanojezra** [comment]
it should be displaying that you need 9615 words

**Comment by timhkim** [comment]
Ah, shoot. I'm going to close this ticket, and re-open a more relevant one.

**Comment by nanojezra** [comment]
thank you
