### ISSUE TITLE
Users aren't able to update their word count on the last day of their goal.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#328]
I have a project that ends today, February 8. My stats are correctly incorporating today as a possible day I can write, but the progress updater in the nav has disappeared as if today is not active.

**Comment by nanojezra** [comment]
this is ready for testing preferably after 3PM PST

**Comment by timhkim** [comment]
This doesn't seem to be working on staging. I have a project called "Testing Staging" that's selected as my primary project. It's scheduled to end today, 2/27 and the word-count updater is not showing in my nav.

**Comment by nanojezra** [comment]
This is not good; the code is working locally but something is skewing the dates on staging.

**Comment by nanojezra** [comment]
please test on staging

and please test again on staging at 2400

**Comment by timhkim** [comment]
Just tested at 14:48 and it's working!

You want me to test again at 2400 or after? Midnight is rough.

**Comment by nanojezra** [comment]
I'm going to set my computer time to 12:01AM and see what happens

**Comment by nanojezra** [comment]
it is definitely not stopping when it should

**Comment by nanojezra** [comment]
oh, there is a lousy bug in the 'create/edit goal' form

**Comment by nanodave** [comment]
What up here, yo?
