### ISSUE TITLE
Some users are unable to log-in to the site.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#333]
From user chillique:

1. The problem I'm having right now is exactly what others have said on this thread. I try to log-in, and it sends me to a page that says "it looks like you haven't created a novel" for less than two seconds, then launches straight back to the homepage. For reference, after I click log-in, it goes to [this page](https://photobucket.com/gallery/http://s1243.photobucket.com/user/rkprincess/media/Screenshot%202019-02-10%2020.08.34_zpsjhjpek0p.png.html), then quickly [flips to this one](http://s1243.photobucket.com/user/rkprincess/media/Screenshot%202019-02-10%2020.08.35_zpsz53s3bmg.png.html), which is very similar, but in the top right corner you can see that I've been logged out. It then lands back on the home page, as if I'd never signed-in at all.
2. I've tried to log-in on several different days, four different browsers (Firefox, Chrome, Safari, and Edge), three different devices (Windows 8 PC, Windows 10 laptop, and a 6th gen iPad), and I've tried the suggested fixes (using an incorrect password first/changing your password). The bug is exactly the same, no matter which combination of those things I used.

Same reports from users Kittyhawk, Emily Jaquez, Aeon Reighn, Evil Queen, sharvil1

**Comment by timhkim** [comment]
We got a fresh batch of reports on this, with a couple users reporting seeing this error:

Error: Attempted to handle event `becameError` on <sign-in-attempt:e6299b63-a039-4791-9877-ff13631ea0f0> while in state root.loaded.created.uncommitted.

Is this related to the server work we're doing? You can see more reports here: https://nanowrimo.org/forums/preview-site-bug-reports/threads/461531

**Comment by nanodave** [comment]
Closed because the issue is a ticket in the api issues.
