### ISSUE TITLE
The "My Daily Word Count" graph does not update correctly when switching between projects on the stats dashboard.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#334]
Similar to #309.

1. Go to the stats dashboard. The "My Daily Word Count" graph in the third row should display information correctly. 
2. Switch to a different project/goal using the dropdown select at the top of the stats dashboard.
3. The "My Daily Word Count" graph still displays the previous goal's information. You can force an update by switching between bar/line graphs.

**Comment by nanojezra** [comment]
ready for testing on preview.nanowrimo.org

**Comment by timhkim** [comment]
This is great. Thank you, Jez!
