### ISSUE TITLE
Styling fixes for the Goals page.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#337]
As an example: https://preview.nanowrimo.org/participants/tim-kim/projects/let-s-test/goals

- [ ] The "Create New Goal" button and filter dropdown menu should be on the same line; ideally where the filter dropdown menu is right now. (The button is a little low.)
- [ ] The filter dropdown menu should be styled like it is on the Projects page. Let's raise the caret, basically.
- [ ] Can we make the items in that dropdown with initial caps "Show All Goals" etc.

**Comment by nanojezra** [comment]
when the actionable elements are on the same line, should they be aligned top, middle, or bottom?

**Comment by timhkim** [comment]
Aligned bottom, please!
