### ISSUE TITLE
Fix the "goals" section when announcing a new project.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#343]
This broke last week during the staging/log-in issues. Can we fix it ASAP?

![goals screen](https://user-images.githubusercontent.com/39069145/53355871-e6f19d00-38de-11e9-94bd-994e0661a7cd.PNG)

**Comment by nanojezra** [comment]
ready for testing on staging

**Comment by timhkim** [comment]
Looks good! Now that staging's involved, what should our workflow be? Should I continue to close tickets if they look good for me, or I guess I could label them "ready for deploy" and you can close them when they are pushed to production?

**Comment by nanojezra** [comment]
Ideally the ticket won't be marked as "closed" until the code has been pushed to production (and tested on production).  There is now a "Ready for Production" label that can be applied to tickets that have passed testing on Staging. I will close the ticket after the fix has been tested on production

**Comment by timhkim** [comment]
Sounds good! Labeled.

**Comment by nanojezra** [comment]
deployed and tested on Production
