### ISSUE TITLE
On the projects page, create a prompt to create a goal for projects that don't yet have an existing goal.

### ISSUE THREAD

**Issue by nanojezra** [nanowrimo/nanowrimo_frontend#346]
The design makes the assumption that all projects have a goal. However, it is possible to be in a state where a project has no associated goal, and this will result in the project listing displaying and empty progress bar with  a goal of "NaN"

**Comment by timhkim** [comment]
Great question. Can we hide the progress bar completely, and then where it currently says "Goal: TKWRITE ### WORDS" make that display "Goal; Set a goal for your project!" and link that to the goal-setting pop-up?

**Comment by nanojezra** [comment]
How about "Set a goal for this project" ?  

For reference, there are 3 ways to enter this state. 
1. delete all goals associated with a project
2. create a project via the API
3. broken import of old data

**Comment by timhkim** [comment]
That works, too! 

Super interesting about the ways that state can happen. Thanks for letting me know, Jez!

**Comment by nanodave** [comment]
Moved to other list
