### ISSUE TITLE
Switching primary projects is not holding consistently.

### ISSUE THREAD

**Issue by timhkim** [nanowrimo/nanowrimo_frontend#359]
1. I have a project and an active goal, and I can update it via the word-count updater in the nav.
2. I created a second project with another active goal.
3. I go to the Projects page and switch the primary project using the project-edit form.
3. I go to the dropdown to update my word count, and it shows the previous primary project goal rather than the one I just switched it to.
4. If I do a refresh of the page, it clears up.

As I was trying to test this, it seems like it's fairly inconsistent as to whether a switch in "primary project" holds. At first I thought, on my test account on staging, it seemed like I can switch TO projects/goals I created earlier easily, but whenever I tried to switch to my newest project/goal, it didn't hold. On further testing, I'm having a hard time finding a pattern for when switching a project automatically works or not. Sometimes I'll switch the primary project, and I'll see that change immediately reflected with the pin icon on the projects page, and with a change in the nav with the word-count updater. Sometimes I won't see a change until I refresh the page. Sometimes I won't see a change even after refreshing the page.

**Comment by nanojezra** [comment]
This issue was caused by a problem in the API. Changes have been made to the API that should resolve this issue. If you are unable to recreate this issue, then this ticket is ready to be closed.

**Comment by timhkim** [comment]
Okay! Here's what I'm seeing on staging:

1. I have two projects, "Camp Project" (newer), and "Testing Stats". "Camp Project" is my primary project. All is well and working as expected.
2. I go to the projects page. I use the dropdown menu to access the project-edit form, and change my primary project to "Testing Stats". This switches the pin, and shows the correct primary project in the nav updater.
3. Without refreshing, I try to change it back to "Camp Project" in the same manner -- using the dropdown menu to access the project-edit form. In that form, I see that "Make this my primary project" is already checked, though it shouldn't be. I cancel without making any changes, and refresh the page.
4. I use the dropdown to access the project-edit form for "Camp Project" again, and this time the box is unchecked. I check it.
5. On the projects page, the pin remains on "Testing Stats". The nav updater is also still displaying "Testing Stats."
6. I refresh the page. The pin is now on "Camp Project" , and the nav updater is also now correctly displaying "Camp Project".

**Comment by timhkim** [comment]
(Also, this still seems like it's happening on both staging and production.)

**Comment by nanojezra** [comment]
At this point, from what I can tell, the API code to resolve this problem has been pushed to both staging and production

**Comment by timhkim** [comment]
Okay! I think this is mostly working, and the lingering issues I'm seeing are probably not normal use cases.

For me, if I switch from "Novel A" to "Novel B", then IMMEDIATELY try to switch back to Novel A, the checkbox remains checked. If I give it a second and then click into the edit form for Novel A, it's then unchecked.

Given the current state, I think we can call this basically closed. Jez, I'm going to leave it to you to change the status!
